language: php
php:
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- '7.1'
addons:

before_install:
    # import deployment key
    - openssl aes-256-cbc -K $encrypted_6a8a01238676_key -iv $encrypted_6a8a01238676_iv -in dfwtr_deploy.enc -out dfwtr_deploy -d
    - rm dfwtr_deploy.enc
    - chmod 600 dfwtr_deploy
    - mv dfwtr_deploy ~/.ssh/id_rsa

before_script:
    - composer install

script:
    - tar -zcvf build.tar.gz builddir

after_success:
    - bash _scripts/deploy.sh
