parameters:
    uploads_dir_path: "%kernel.root_dir%/../web/uploads"


services:
    app.city_report.importer:
        class: AppBundle\CityReport\Importer
        arguments:
          - "@app.services.pdf_scraper"
          - "@app.city_report.parser"
          - "@doctrine.orm.default_entity_manager"

    app.city_report.parser:
        class: AppBundle\CityReport\CityReportParser
        arguments: ["@app.pdf_scraper.row_parser_factory"]

    app.pdf_scraper.row_parser_factory:
        class: AppBundle\CityReport\RowParserFactory

    app.services.pdf_scraper:
        class: AppBundle\Services\PdfScraper
        arguments:
          - "%uploads_dir_path%"
          - "@kreatys.pdf_parser"
