parameters:
    uploads_dir_path: "%kernel.root_dir%/../web/uploads"


services:
    app.pdf_scraper:
        class: AppBundle\PdfScraper\PdfScraper
        arguments: ["@kreatys.pdf_parser", "@app.pdf_scraper.data_point_parser_factory"]

    app.pdf_scraper.data_point_parser_factory:
        class: AppBundle\PdfScraper\DataPointParserFactory

    app.importer.default:
        class: AppBundle\Importer\CityReportImporter
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "%uploads_dir_path%"
