parameters:
    temp_uploads_dir_path: "%kernel.root_dir%/../web/temp"
    carr_report_uploads_path: "%temp_uploads_dir_path%/carr_reports"


services:
    app.city_report.importer:
        class: AppBundle\CityReport\Importer
        arguments:
          - "@app.services.pdf_scraper"
          - "@app.city_report.parser"
          - "@doctrine.orm.default_entity_manager"

    app.city_report.parser:
        class: AppBundle\CityReport\CityReportParser
        arguments: ["@app.pdf_scraper.row_parser_factory"]

    app.pdf_scraper.row_parser_factory:
        class: AppBundle\CityReport\RowParserFactory

    app.services.pdf_scraper:
        class: AppBundle\Services\PdfScraper
        arguments:
          - "@filesystem"
          - "%carr_report_uploads_path%"
          - "@kreatys.pdf_parser"
